dubbo :
  protocol :
    port : 20880
    name  : dubbo
  application :
    name : study-provider
  registry :
    address : zookeeper://127.0.0.1:2181
  packageName : com.xujie.controller
spring:
  mvc:
    view:
      prefix: /
      suffix: .html
server:
  port: 8085

